# Generated by Django 2.1.7 on 2021-03-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210323_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=16, max_digits=8),
        ),
    ]
